#exclude-tools: # Uncomment the tools you want to exclude from analysis
  #- semgrep
  #- bandit
  #- find-sec-bugs
  #- osv-scanner
  #- trivy-sca
  #- gitleaks
  #- checkov
  #- syft

tools-config:
  semgrep:
    api-key:  # Semgrep API key
  checkov:
    api-key:  #"Add an api key '--bc-api-key <api-key>' to see more detailed insights via https://bridgecrew.cloud"

containers:
  image: ""