containers:
  security-tools:
    sast: 
      semgrep: 
        image: "returntocorp/semgrep"
        version: "1.41.0"
        command: "semgrep scan --config=auto --output /src/security-tools/semgrep_results.json --json"
    sca:
      dependency-check:
        image: "owasp/dependency-check"
        version: "8.4.0"
        command: "--scan /src --format XML --project dependency-check-scan --out /src/security-tools --enableExperimental"
    containers:
      trivy:
        image: "aquasec/trivy"
        version: "0.45.1"
        command: "fs --scanners vuln,config /src -f json -o /src/security-tools/trivy_results.json"
    secrets-scanning:
      gitleaks:
        image: "zricethezav/gitleaks"
        version: "v8.18.0"
        command: "detect --source /src -f json -r /src/security-tools/gitleaks_results.json"